# attendees/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import home_view, AttendeeProfileViewSet, TimelineAPIView

# The router automatically generates URLs for the ViewSet
router = DefaultRouter()
router.register(r'profiles', AttendeeProfileViewSet, basename='attendeeprofile')

urlpatterns = [
    # The homepage that serves your HTML file
    path('', home_view, name='home'),

    # The API endpoint for the timeline
    path('api/timeline/', TimelineAPIView.as_view(), name='api-timeline'),

    # All API URLs generated by the router for profiles
    # (e.g., /api/attendees/profiles/, /api/attendees/profiles/1/)
    path('api/attendees/', include(router.urls)),
]