# Generated by Django 5.2.6 on 2025-09-23 16:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='first_time_attendee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='networking_preferences',
            field=models.CharField(choices=[('open', 'Open to networking'), ('selective', 'Selective networking'), ('minimal', 'Minimal networking')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed'), ('registered', 'Registered'), ('attended', 'Attended'), ('bookmarked', 'Bookmarked'), ('rated', 'Rated')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('notes', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendeeprofile')),
            ],
            options={
                'unique_together': {('attendee', 'event_id', 'interaction_type')},
            },
        ),
    ]
